-- 銓宏國際 - Supabase Auth Hook 修復版本
-- 修復 custom_access_token_hook 的錯誤

-- ============================================
-- 步驟 1: 刪除舊的 hook（如果有）
-- ============================================

DROP FUNCTION IF EXISTS public.custom_access_token_hook(jsonb) CASCADE;

-- ============================================
-- 步驟 2: 確保角色類型存在
-- ============================================

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'app_role') THEN
        CREATE TYPE public.app_role AS ENUM ('admin', 'sales', 'accounting', 'design', 'guest');
    END IF;
END
$$;

-- ============================================
-- 步驟 3: 確保使用者角色表存在
-- ============================================

CREATE TABLE IF NOT EXISTS public.user_roles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
    role public.app_role NOT NULL DEFAULT 'guest',
    name text,
    created_at timestamp with time zone DEFAULT now(),
    UNIQUE (user_id, role)
);

-- ============================================
-- 步驟 4: 啟用 RLS
-- ============================================

ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

-- 刪除舊的 policy（如果有）
DROP POLICY IF EXISTS "Allow auth admin to read user roles" ON public.user_roles;

CREATE POLICY "Allow auth admin to read user roles" ON public.user_roles
    FOR SELECT TO supabase_auth_admin USING (true);

-- ============================================
-- 步驟 5: 建立修復後的 Auth Hook 函數
-- ============================================

CREATE OR REPLACE FUNCTION public.custom_access_token_hook(event jsonb)
RETURNS jsonb 
LANGUAGE plpgsql 
STABLE 
SECURITY DEFINER
AS $$
DECLARE
    claims jsonb;
    user_id uuid;
    user_role public.app_role;
    user_name text;
    user_email text;
BEGIN
    -- 安全地取得 user_id
    BEGIN
        user_id := (event->>'user_id')::uuid;
    EXCEPTION WHEN OTHERS THEN
        -- 如果轉換失敗，直接返回原始 event
        RETURN event;
    END;
    
    -- 如果沒有 user_id，直接返回
    IF user_id IS NULL THEN
        RETURN event;
    END IF;
    
    -- 取得 claims
    claims := event->'claims';
    IF claims IS NULL THEN
        claims := '{}'::jsonb;
    END IF;
    
    -- 取得 email（從 claims 或 token）
    user_email := claims->>'email';
    IF user_email IS NULL THEN
        user_email := event->>'email';
    END IF;
    
    -- 查詢使用者角色（使用例外處理避免錯誤）
    BEGIN
        SELECT ur.role, ur.name 
        INTO user_role, user_name
        FROM public.user_roles ur
        WHERE ur.user_id = user_id
        LIMIT 1;
    EXCEPTION WHEN OTHERS THEN
        -- 查詢失敗時使用預設值
        user_role := NULL;
        user_name := NULL;
    END;
    
    -- 如果沒有找到角色，嘗試從 email 推斷
    IF user_role IS NULL THEN
        IF user_email LIKE 'wugys@%' THEN
            user_role := 'admin';
            user_name := 'Kevin';
        ELSIF user_email LIKE 'zizi@%' THEN
            user_role := 'sales';
            user_name := '姿姿';
        ELSIF user_email LIKE 'mia@%' THEN
            user_role := 'accounting';
            user_name := 'Mia';
        ELSIF user_email LIKE 'betty@%' THEN
            user_role := 'sales';
            user_name := 'Betty';
        ELSE
            user_role := 'guest';
            user_name := user_email;
        END IF;
    END IF;
    
    -- 設定 claims
    claims := jsonb_set(claims, '{user_role}', to_jsonb(user_role));
    
    IF user_name IS NOT NULL THEN
        claims := jsonb_set(claims, '{name}', to_jsonb(user_name));
    ELSIF user_email IS NOT NULL THEN
        claims := jsonb_set(claims, '{name}', to_jsonb(user_email));
    END IF;
    
    -- 更新 event
    event := jsonb_set(event, '{claims}', claims);
    
    RETURN event;
END;
$$;

-- ============================================
-- 步驟 6: 授權
-- ============================================

GRANT USAGE ON SCHEMA public TO supabase_auth_admin;
GRANT EXECUTE ON FUNCTION public.custom_access_token_hook(jsonb) TO supabase_auth_admin;

-- 確保其他角色沒有執行權限
REVOKE EXECUTE ON FUNCTION public.custom_access_token_hook(jsonb) FROM authenticated, anon, public;

-- ============================================
-- 完成！請到 Authentication → Hooks 啟用 Access Token Hook
-- Hook 設定：
--   - Type: Access Token
--   - URL: pg-functions://postgres/public/custom_access_token_hook
-- ============================================

SELECT '✅ Auth Hook 修復完成！' as status;
